### ISSUE TITLE
dsc_service doesn't refresh on notify

### ISSUE THREAD

**Issue by ktreese** [puppetlabs/puppetlabs-dsc#217]
The dsc_service doesn't appear to support the “refresh” action when a dependency changes via notify.  It does, however, ensure a service is running when stopped.

Therefore, I have to use the native service type as well to handle this situation.

```
  service { $service_name:
    ensure    => running,
    enable    => true,
    subscribe => Dsc_service[$service_name],
  }

  #Prevents user from changing service to run as Local System account
  dsc_service { $service_name:
    dsc_name       => $service_name,
    dsc_credential => {"user" => "${service_user}", "password" => "${service_pass}"},
  }
```

**Comment by ferventcoder** [comment]
@ktreese This is likely related to the DSC resource itself not having a good way to query the state of the service (this boils down to Get, Test, Set) and Microsoft's prior focus on not worrying about Test as much as Get and Set. Expect things to come up more to speed as the underlying DSC resources get better.

**Comment by ktreese** [comment]
@ferventcoder Thanks for that.  Though use of service and dsc_service works just fine, it felt kludgy.

**Comment by ferventcoder** [comment]
I was corrected. It was Get that was not a focus awhile back. So sometimes things come back empty or without data.

**Comment by ktreese** [comment]
Likewise, dsc_service doesn't pick up on user password changes and update services using said account.

**Comment by Iristyle** [comment]
@ktreese out of curiosity - is there a deficiency in the Puppet service type that made you want to use the DSC one?

**Comment by ktreese** [comment]
@Iristyle yes.  The native service type does not support configuring service dependencies or account to run as.  As such, I was looking to control drift / prevent a user from changing a service to run as the Local System account.

**Comment by c22** [comment]
Should this be closed? It looks like it still happens.

Will there be no changes required in puppetlabs-dsc once the DSC resource comes up to speed?

**Comment by ktreese** [comment]
@c22 I had closed the issue since the use of the native service type coupled with the dsc_service resource type gave me what I needed. Ultimately, that in itself is still an issue, as is the inability to recognize password changes. I'll reopen

**Comment by jpogran** [comment]
Hi,

Puppet will be shutting down the github issues tab in this repository as there already is a publicly accessible [issue tracker](https://tickets.puppetlabs.com/browse/MODULES) on March 24th, 20017.

If you want to continue the discussion from this issue, please follow the ticket already created from this issue (typically MODULES-XXXX) in our issue tracker.

If you would like to file a new issue, please follow the [template here](https://tickets.puppetlabs.com/CreateIssue.jspa?pid=10707) to create a new ticket.

Thanks,

James Pogran

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.\n\nWe're going to close it but please do raise another issue if the issue still persists. 😄
